### ISSUE TITLE
closure actions is not supported 

### ISSUE THREAD

**Issue by anthonynasrkeeward** [miguelcobain/ember-dynamic-render-template#2]
what should I do to make it work? i have used the addon as below:
` {{render-template templateString="String: {{a}} + {{b}} = {{c}} - {{my-component prop=(action 'actionName')}}" props=(hash a=1 b=1 c=2)}}`

**The error was:**
>  ember.debug.js:18023 Assertion Failed: An action named 'actionName' was not found in <k-framework-front-end@component:dynamic-ember884::ember891>

_but the action exist_

**Comment by linux2647** [comment]
You can pass the action along in your props.  Something like:
```{{render-template templateString="String: {{a}} + {{b}} = {{c}} - {{my-component prop=someAction}}" props=(hash a=1 b=1 c=2 someAction=(action 'actionName'))}}```
